services:
  gogrepo:
    build: .
    container_name: gogrepo
    working_dir: /downloads
    volumes:
      - C:/gog-archive/downloads:/downloads  # Where your games will be saved
      - C:/Users/scotb/.config/lgogdownloader:/root/.config/lgogdownloader  # Persist your lgogdownloader config
